//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class AddCompany
{
    public int TrackID { get; set; }
    public string Userlevel { get; set; }
    public string CompanyReg { get; set; }
    public string CompanyName { get; set; }
    public string Email { get; set; }
    public string StartDate { get; set; }
    public string EndDate { get; set; }
    public string EmpPrice { get; set; }
    public Nullable<int> Count { get; set; }
}

public partial class Allowance
{
    public int AllowancesID { get; set; }
    public int CID { get; set; }
    public string AllowancesName { get; set; }
    public Nullable<double> Amount { get; set; }

    public virtual Company Company { get; set; }
    public virtual Company Company1 { get; set; }
}

public partial class ApplyJob
{
    public int TEID { get; set; }
    public Nullable<int> VID { get; set; }
    public Nullable<int> CID { get; set; }
    public string Ename { get; set; }
    public string Email { get; set; }
    public string Introduction { get; set; }
    public string WorkingEx { get; set; }
    public string Edu { get; set; }
    public string Salary { get; set; }
    public string Resume { get; set; }
    public string Status { get; set; }
    public string Designation { get; set; }
    public Nullable<System.DateTime> Modified { get; set; }

    public virtual Company Company { get; set; }
    public virtual Company Company1 { get; set; }
    public virtual Vacancy Vacancy { get; set; }
    public virtual Vacancy Vacancy1 { get; set; }
}

public partial class AssignRoster
{
    public int AssignID { get; set; }
    public int EID { get; set; }
    public string Job { get; set; }
    public string JLocation { get; set; }
    public double JLocation_lat { get; set; }
    public double JLocation_longi { get; set; }
    public string Instructions { get; set; }
    public byte[] Special { get; set; }
    public string Contact { get; set; }
    public System.DateTime Roster_Cycle { get; set; }
    public System.TimeSpan StartTime { get; set; }
    public System.TimeSpan EndTime { get; set; }
    public Nullable<int> JobID { get; set; }
    public string Status { get; set; }

    public virtual Employee Employee { get; set; }
    public virtual Employee Employee1 { get; set; }
}

public partial class Attendance
{
    public int AID { get; set; }
    public Nullable<int> WID { get; set; }
    public int EID { get; set; }
    public Nullable<System.DateTime> StartDateTime { get; set; }
    public Nullable<System.DateTime> EndDateTime { get; set; }
    public string Mark { get; set; }

    public virtual Employee Employee { get; set; }
    public virtual Employee Employee1 { get; set; }
    public virtual Work Work { get; set; }
    public virtual Work Work1 { get; set; }
}

public partial class BankDetail
{
    public int BID { get; set; }
    public Nullable<int> EID { get; set; }
    public string BankName { get; set; }
    public string FullName { get; set; }
    public string AccountNumber { get; set; }
    public string Branch { get; set; }

    public virtual Employee Employee { get; set; }
    public virtual Employee Employee1 { get; set; }
}

public partial class Company
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Company()
    {
        this.Allowances = new HashSet<Allowance>();
        this.Allowances1 = new HashSet<Allowance>();
        this.ApplyJobs = new HashSet<ApplyJob>();
        this.ApplyJobs1 = new HashSet<ApplyJob>();
        this.Employees = new HashSet<Employee>();
        this.Employees1 = new HashSet<Employee>();
        this.HRDocuments = new HashSet<HRDocument>();
        this.HRDocuments1 = new HashSet<HRDocument>();
        this.LeaveManagments = new HashSet<LeaveManagment>();
        this.LeaveManagments1 = new HashSet<LeaveManagment>();
        this.Planners = new HashSet<Planner>();
        this.Planners1 = new HashSet<Planner>();
        this.PolicyDocuments = new HashSet<PolicyDocument>();
        this.PolicyDocuments1 = new HashSet<PolicyDocument>();
        this.ResourceFiles = new HashSet<ResourceFile>();
        this.ResourceFiles1 = new HashSet<ResourceFile>();
        this.Vacancies = new HashSet<Vacancy>();
        this.Vacancies1 = new HashSet<Vacancy>();
    }

    public int CID { get; set; }
    public string Company_name { get; set; }
    public string Country { get; set; }
    public string Reg_No { get; set; }
    public string Tax { get; set; }
    public string Tel { get; set; }
    public string CompanyEmail { get; set; }
    public string Eaddress { get; set; }
    public string Admin_Password { get; set; }
    public string Hr_Password { get; set; }
    public string Description { get; set; }
    public string AdminEmail { get; set; }
    public string HREmail { get; set; }
    public string FinanceEmail { get; set; }
    public string OTP { get; set; }
    public string Membership { get; set; }
    public string StartDate { get; set; }
    public string EndDate { get; set; }
    public string WorkingDays { get; set; }
    public string EPF1 { get; set; }
    public string EPF2 { get; set; }
    public string ETF { get; set; }
    public string PurchaseStatus { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Allowance> Allowances { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Allowance> Allowances1 { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ApplyJob> ApplyJobs { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ApplyJob> ApplyJobs1 { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Employee> Employees { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Employee> Employees1 { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<HRDocument> HRDocuments { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<HRDocument> HRDocuments1 { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<LeaveManagment> LeaveManagments { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<LeaveManagment> LeaveManagments1 { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Planner> Planners { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Planner> Planners1 { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<PolicyDocument> PolicyDocuments { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<PolicyDocument> PolicyDocuments1 { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ResourceFile> ResourceFiles { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ResourceFile> ResourceFiles1 { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Vacancy> Vacancies { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Vacancy> Vacancies1 { get; set; }
}

public partial class ContactU
{
    public int ContacID { get; set; }
    public Nullable<int> EID { get; set; }
    public string Name { get; set; }
    public string Email { get; set; }
    public Nullable<int> ContactNumber { get; set; }
    public string Message { get; set; }

    public virtual Employee Employee { get; set; }
    public virtual Employee Employee1 { get; set; }
}

public partial class DateDiff
{
    public string StartDate { get; set; }
    public string EndDate { get; set; }
    public int EID { get; set; }
    public int AID { get; set; }
}

public partial class DeclinedRoster
{
    public int DID { get; set; }
    public int EID { get; set; }
    public string Job { get; set; }
    public string JLocation { get; set; }
    public double JLocation_lat { get; set; }
    public double JLocation_longi { get; set; }
    public string Instructions { get; set; }
    public byte[] Special { get; set; }
    public string Contact { get; set; }
    public System.DateTime Roster_Cycle { get; set; }
    public string JobStatus { get; set; }
    public Nullable<int> JobID { get; set; }
    public string StartTime { get; set; }
    public string EndTime { get; set; }

    public virtual JobContractCasual JobContractCasual { get; set; }
    public virtual JobContractCasual JobContractCasual1 { get; set; }
    public virtual Employee Employee { get; set; }
    public virtual Employee Employee1 { get; set; }
}

public partial class EmergencyContact
{
    public int ECID { get; set; }
    public Nullable<int> EID { get; set; }
    public string Name { get; set; }
    public string Contact { get; set; }
    public string Relationship { get; set; }

    public virtual Employee Employee { get; set; }
    public virtual Employee Employee1 { get; set; }
}

public partial class Employee
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Employee()
    {
        this.AssignRosters = new HashSet<AssignRoster>();
        this.AssignRosters1 = new HashSet<AssignRoster>();
        this.Attendances = new HashSet<Attendance>();
        this.Attendances1 = new HashSet<Attendance>();
        this.BankDetails = new HashSet<BankDetail>();
        this.BankDetails1 = new HashSet<BankDetail>();
        this.DeclinedRosters = new HashSet<DeclinedRoster>();
        this.DeclinedRosters1 = new HashSet<DeclinedRoster>();
        this.EmergencyContacts = new HashSet<EmergencyContact>();
        this.EmergencyContacts1 = new HashSet<EmergencyContact>();
        this.ContactUs = new HashSet<ContactU>();
        this.ContactUs1 = new HashSet<ContactU>();
        this.EmployeeLeaves = new HashSet<EmployeeLeaf>();
        this.EmployeeLeaves1 = new HashSet<EmployeeLeaf>();
        this.JobContractCasuals = new HashSet<JobContractCasual>();
        this.JobContractPermenents = new HashSet<JobContractPermenent>();
        this.JobContractCasuals1 = new HashSet<JobContractCasual>();
        this.JobContractPermenents1 = new HashSet<JobContractPermenent>();
        this.LeaveManagmentDetails = new HashSet<LeaveManagmentDetail>();
        this.LeaveManagmentDetails1 = new HashSet<LeaveManagmentDetail>();
        this.ReportIncidents = new HashSet<ReportIncident>();
        this.ReportIncidents1 = new HashSet<ReportIncident>();
        this.Resigns = new HashSet<Resign>();
        this.Resigns1 = new HashSet<Resign>();
        this.Rosters = new HashSet<Roster>();
        this.Rosters1 = new HashSet<Roster>();
        this.Roster_tracker = new HashSet<Roster_tracker>();
        this.Roster_tracker1 = new HashSet<Roster_tracker>();
        this.UploadResumes = new HashSet<UploadResume>();
        this.UploadResumes1 = new HashSet<UploadResume>();
        this.Works = new HashSet<Work>();
        this.Works1 = new HashSet<Work>();
    }

    public Nullable<int> CompanyID { get; set; }
    public int EID { get; set; }
    public string Ename { get; set; }
    public string DOB { get; set; }
    public string Country { get; set; }
    public string VisaStatus { get; set; }
    public string OtherReasons { get; set; }
    public string DriversLicense_NIC { get; set; }
    public string Tel { get; set; }
    public string Email { get; set; }
    public string Eaddress { get; set; }
    public string EmployeementType { get; set; }
    public string ContractType { get; set; }
    public string AvailableDays { get; set; }
    public string Epassword { get; set; }
    public string Gender { get; set; }
    public string Language { get; set; }
    public string MaritalStatus { get; set; }
    public string Hqualification { get; set; }
    public string Qname { get; set; }
    public string otherQ { get; set; }
    public string bloodGrp { get; set; }
    public string specialReq { get; set; }
    public string otherReq { get; set; }
    public string Leaves { get; set; }
    public string NopayDays { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<AssignRoster> AssignRosters { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<AssignRoster> AssignRosters1 { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Attendance> Attendances { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Attendance> Attendances1 { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<BankDetail> BankDetails { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<BankDetail> BankDetails1 { get; set; }
    public virtual Company Company { get; set; }
    public virtual Company Company1 { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<DeclinedRoster> DeclinedRosters { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<DeclinedRoster> DeclinedRosters1 { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<EmergencyContact> EmergencyContacts { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<EmergencyContact> EmergencyContacts1 { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ContactU> ContactUs { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ContactU> ContactUs1 { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<EmployeeLeaf> EmployeeLeaves { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<EmployeeLeaf> EmployeeLeaves1 { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<JobContractCasual> JobContractCasuals { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<JobContractPermenent> JobContractPermenents { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<JobContractCasual> JobContractCasuals1 { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<JobContractPermenent> JobContractPermenents1 { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<LeaveManagmentDetail> LeaveManagmentDetails { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<LeaveManagmentDetail> LeaveManagmentDetails1 { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ReportIncident> ReportIncidents { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ReportIncident> ReportIncidents1 { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Resign> Resigns { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Resign> Resigns1 { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Roster> Rosters { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Roster> Rosters1 { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Roster_tracker> Roster_tracker { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Roster_tracker> Roster_tracker1 { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<UploadResume> UploadResumes { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<UploadResume> UploadResumes1 { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Work> Works { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Work> Works1 { get; set; }
}

public partial class EmployeeLeaf
{
    public int EmpLeaveID { get; set; }
    public Nullable<int> LID { get; set; }
    public Nullable<int> EID { get; set; }
    public Nullable<int> Casual { get; set; }
    public Nullable<int> Annual { get; set; }
    public Nullable<int> Sick { get; set; }
    public Nullable<int> Maternity { get; set; }
    public Nullable<int> NoPay { get; set; }

    public virtual Employee Employee { get; set; }
    public virtual Employee Employee1 { get; set; }
    public virtual LeaveManagment LeaveManagment { get; set; }
    public virtual LeaveManagment LeaveManagment1 { get; set; }
    public virtual LeaveManagment LeaveManagment2 { get; set; }
    public virtual LeaveManagment LeaveManagment3 { get; set; }
}

public partial class EmployementType
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public EmployementType()
    {
        this.LeaveManagments = new HashSet<LeaveManagment>();
        this.LeaveManagments1 = new HashSet<LeaveManagment>();
    }

    public int EmpTID { get; set; }
    public string Type { get; set; }
    public string ContractType { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<LeaveManagment> LeaveManagments { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<LeaveManagment> LeaveManagments1 { get; set; }
}

public partial class HourDiffTotWorkHour
{
    public Nullable<int> TotWorkHours { get; set; }
    public int EID { get; set; }
}

public partial class HRDocument
{
    public int DocID { get; set; }
    public Nullable<int> CID { get; set; }
    public string Name { get; set; }
    public string ContentType { get; set; }
    public byte[] Data { get; set; }

    public virtual Company Company { get; set; }
    public virtual Company Company1 { get; set; }
}

public partial class JobContractCasual
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public JobContractCasual()
    {
        this.DeclinedRosters = new HashSet<DeclinedRoster>();
        this.DeclinedRosters1 = new HashSet<DeclinedRoster>();
        this.Rosters = new HashSet<Roster>();
        this.Rosters1 = new HashSet<Roster>();
    }

    public int JID { get; set; }
    public int EID { get; set; }
    public string Selected_Jobs { get; set; }
    public string Experiance { get; set; }
    public string Hourly_rate { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<DeclinedRoster> DeclinedRosters { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<DeclinedRoster> DeclinedRosters1 { get; set; }
    public virtual Employee Employee { get; set; }
    public virtual Employee Employee1 { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Roster> Rosters { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Roster> Rosters1 { get; set; }
}

public partial class JobContractPermenent
{
    public int JID { get; set; }
    public int EID { get; set; }
    public string Designation { get; set; }
    public string Experiance { get; set; }
    public string Salary { get; set; }
    public string Hourly_rate { get; set; }

    public virtual Employee Employee { get; set; }
    public virtual Employee Employee1 { get; set; }
}

public partial class LeaveManagment
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public LeaveManagment()
    {
        this.EmployeeLeaves = new HashSet<EmployeeLeaf>();
        this.EmployeeLeaves1 = new HashSet<EmployeeLeaf>();
        this.EmployeeLeaves2 = new HashSet<EmployeeLeaf>();
        this.EmployeeLeaves3 = new HashSet<EmployeeLeaf>();
    }

    public int LID { get; set; }
    public Nullable<int> CID { get; set; }
    public int EmpTID { get; set; }
    public Nullable<int> Casual { get; set; }
    public Nullable<int> Annual { get; set; }
    public Nullable<int> Sick { get; set; }
    public Nullable<int> Maternity { get; set; }
    public Nullable<int> NoPay { get; set; }

    public virtual Company Company { get; set; }
    public virtual Company Company1 { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<EmployeeLeaf> EmployeeLeaves { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<EmployeeLeaf> EmployeeLeaves1 { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<EmployeeLeaf> EmployeeLeaves2 { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<EmployeeLeaf> EmployeeLeaves3 { get; set; }
    public virtual EmployementType EmployementType { get; set; }
    public virtual EmployementType EmployementType1 { get; set; }
}

public partial class LeaveManagmentDetail
{
    public int LMID { get; set; }
    public int EID { get; set; }
    public string EmpName { get; set; }
    public string Department { get; set; }
    public string Manager { get; set; }
    public string LeaveType { get; set; }
    public string NoOfDays { get; set; }
    public Nullable<System.DateTime> Date { get; set; }
    public string Reason { get; set; }
    public string Status { get; set; }

    public virtual Employee Employee { get; set; }
    public virtual Employee Employee1 { get; set; }
}

public partial class OTP
{
    public int TrackID { get; set; }
    public string OTP1 { get; set; }
    public string packageType { get; set; }
    public string CompanyReg { get; set; }
    public string CompanyName { get; set; }
    public string Price { get; set; }
    public string Email { get; set; }
    public string StartDate { get; set; }
    public string DueDate { get; set; }
    public string Ptype { get; set; }
}

public partial class Package
{
    public int PID { get; set; }
    public string Pname { get; set; }
    public string PricePerEmp { get; set; }
}

public partial class Payment
{
    public int PID { get; set; }
    public int EID { get; set; }
    public int Basic { get; set; }
    public int Allowances { get; set; }
    public int Deductions { get; set; }
    public Nullable<int> NetPay { get; set; }
    public Nullable<int> ETF3 { get; set; }
    public Nullable<int> EPF8 { get; set; }
    public Nullable<int> EPF12 { get; set; }
    public string Month { get; set; }
}

public partial class PaymentInvoice
{
    public int InvoiceID { get; set; }
    public string EID { get; set; }
    public string RosterID { get; set; }
    public string Ename { get; set; }
    public string Job { get; set; }
    public string Paycycle { get; set; }
    public string WorkedHours { get; set; }
    public string HourRate { get; set; }
    public string Tax { get; set; }
    public Nullable<decimal> GrossPayment { get; set; }
}

public partial class Planner
{
    public int PID { get; set; }
    public int CID { get; set; }
    public string Task { get; set; }
    public string Subtask { get; set; }
    public string Dailytarget { get; set; }
    public Nullable<System.DateTime> StartDate { get; set; }
    public Nullable<System.DateTime> EndDate { get; set; }
    public string Assignto { get; set; }

    public virtual Company Company { get; set; }
    public virtual Company Company1 { get; set; }
}

public partial class PolicyDocument
{
    public int DocID { get; set; }
    public Nullable<int> CID { get; set; }
    public string Name { get; set; }
    public string ContentType { get; set; }
    public byte[] Data { get; set; }

    public virtual Company Company { get; set; }
    public virtual Company Company1 { get; set; }
}

public partial class ReportIncident
{
    public int ReportID { get; set; }
    public Nullable<int> EID { get; set; }
    public string Isinvolved { get; set; }
    public string Date { get; set; }
    public string Time { get; set; }
    public string Location { get; set; }
    public string Description { get; set; }

    public virtual Employee Employee { get; set; }
    public virtual Employee Employee1 { get; set; }
}

public partial class Resign
{
    public int RID { get; set; }
    public int EID { get; set; }
    public string Ename { get; set; }
    public string To_ { get; set; }
    public string From_ { get; set; }
    public string Subject_ { get; set; }
    public string Body { get; set; }

    public virtual Employee Employee { get; set; }
    public virtual Employee Employee1 { get; set; }
}

public partial class ResourceFile
{
    public Nullable<int> CID { get; set; }
    public int ID { get; set; }
    public string Name { get; set; }
    public string ContentType { get; set; }
    public byte[] Data { get; set; }

    public virtual Company Company { get; set; }
    public virtual Company Company1 { get; set; }
}

public partial class Roster
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Roster()
    {
        this.Roster_tracker = new HashSet<Roster_tracker>();
        this.Roster_tracker1 = new HashSet<Roster_tracker>();
    }

    public int RosterID { get; set; }
    public Nullable<int> EID { get; set; }
    public string Job { get; set; }
    public string JLocation { get; set; }
    public double JLocation_lat { get; set; }
    public double JLocation_longi { get; set; }
    public string Instructions { get; set; }
    public byte[] Special { get; set; }
    public string Contact { get; set; }
    public System.DateTime Roster_Cycle { get; set; }
    public string JobStatus { get; set; }
    public Nullable<int> JobID { get; set; }
    public string StartTime { get; set; }
    public string EndTime { get; set; }

    public virtual Employee Employee { get; set; }
    public virtual Employee Employee1 { get; set; }
    public virtual JobContractCasual JobContractCasual { get; set; }
    public virtual JobContractCasual JobContractCasual1 { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Roster_tracker> Roster_tracker { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Roster_tracker> Roster_tracker1 { get; set; }
}

public partial class Roster_tracker
{
    public int TrackerID { get; set; }
    public Nullable<int> RosterID { get; set; }
    public Nullable<int> EID { get; set; }
    public string JLocation { get; set; }
    public string JLocation_lat { get; set; }
    public string JLocation_longi { get; set; }
    public string Start_lat { get; set; }
    public string Start_longi { get; set; }
    public string End_lat { get; set; }
    public string End_longi { get; set; }
    public Nullable<System.TimeSpan> Start_time { get; set; }
    public Nullable<System.TimeSpan> End_time { get; set; }
    public Nullable<System.DateTime> Sdate { get; set; }
    public Nullable<System.DateTime> Edate { get; set; }
    public string PaymentStatus { get; set; }

    public virtual Employee Employee { get; set; }
    public virtual Employee Employee1 { get; set; }
    public virtual Roster Roster { get; set; }
    public virtual Roster Roster1 { get; set; }
}

public partial class sysdiagram
{
    public string name { get; set; }
    public int principal_id { get; set; }
    public int diagram_id { get; set; }
    public Nullable<int> version { get; set; }
    public byte[] definition { get; set; }
}

public partial class tblFile
{
    public int id { get; set; }
    public string Name { get; set; }
    public string ContentType { get; set; }
    public byte[] Data { get; set; }
}

public partial class UploadResume
{
    public Nullable<int> EID { get; set; }
    public int ID { get; set; }
    public string Name { get; set; }
    public string ContentType { get; set; }
    public byte[] Data { get; set; }

    public virtual Employee Employee { get; set; }
    public virtual Employee Employee1 { get; set; }
}

public partial class Vacancy
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Vacancy()
    {
        this.ApplyJobs = new HashSet<ApplyJob>();
        this.ApplyJobs1 = new HashSet<ApplyJob>();
    }

    public int VID { get; set; }
    public Nullable<int> CID { get; set; }
    public string Cname { get; set; }
    public string JobTitle { get; set; }
    public string Description { get; set; }
    public string Location { get; set; }
    public string Position { get; set; }
    public string EmployementType { get; set; }
    public string ContractType { get; set; }
    public string SpecialReq { get; set; }
    public string Skills { get; set; }
    public string ReqWorkingEx { get; set; }
    public string RequredEdu { get; set; }
    public string Salary { get; set; }
    public string Working_hours { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ApplyJob> ApplyJobs { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ApplyJob> ApplyJobs1 { get; set; }
    public virtual Company Company { get; set; }
    public virtual Company Company1 { get; set; }
}

public partial class Work
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Work()
    {
        this.Attendances = new HashSet<Attendance>();
        this.Attendances1 = new HashSet<Attendance>();
    }

    public int WID { get; set; }
    public int EID { get; set; }
    public string Location { get; set; }
    public string LocationLat { get; set; }
    public string LocationLongi { get; set; }
    public Nullable<System.TimeSpan> StartTime { get; set; }
    public Nullable<System.TimeSpan> EndTime { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Attendance> Attendances { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Attendance> Attendances1 { get; set; }
    public virtual Employee Employee { get; set; }
    public virtual Employee Employee1 { get; set; }
}

public partial class sp_helpdiagramdefinition_Result
{
    public Nullable<int> version { get; set; }
    public byte[] definition { get; set; }
}

public partial class sp_helpdiagrams_Result
{
    public string Database { get; set; }
    public string Name { get; set; }
    public int ID { get; set; }
    public string Owner { get; set; }
    public int OwnerID { get; set; }
}
